id = "dark-castle"
name = "dark castle"
version = "0.0.1"
schema_version = 1
authors = ["malucart"]
description = "A very dark, colorful theme for focus and readability"
repository = "https://github.com/malucard/dark-castle-theme-zed"
